const r2pipe = r2pipe.open('/bin/ls')
export c
/** Declaration file generated by dts-gen */

export const options: any[];

export const r2bin: string;

export function connect(uri: any, cb: any): void;

export function ioplugin(cb: any): void;

export function jsonParse(p0: any, p1: any): any;

export function launch(file: any, opts: any, cb: any): void;

export function listen(file: any, cb: any): void;

export function lpipe(cb: any): void;

export function lpipeSync(): any;

export function open(...args: any[]): any;

export function openBuffer(buf: any, cb: any): void;

export function openSync(...args: any[]): any;

export function pipe(file: any, opts: any, cb: any): void;

export function pipeSync(file: any, opts: any): any;

export function syscmd(command: any, childOpts: any, cb: any): void;

export function syscmdj(command: any, cb2: any): void;

export namespace connect {
    const prototype: {
    };

}

export namespace ioplugin {
    const prototype: {
    };

}

export namespace launch {
    const prototype: {
    };

}

export namespace listen {
    const prototype: {
    };

}

export namespace lpipe {
    const prototype: {
    };

}

export namespace lpipeSync {
    const prototype: {
    };

}

export namespace open {
    const prototype: {
    };

}

export namespace openBuffer {
    const prototype: {
    };

}

export namespace openSync {
    const prototype: {
    };

}

export namespace pipe {
    const prototype: {
    };

}

export namespace pipeSync {
    const prototype: {
    };

}

export namespace syscmd {
    const prototype: {
    };

}

export namespace syscmdj {
    const prototype: {
    };

}

