name: CI

on: push

jobs:
  build:
    name: r2pipe
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools
    - name: Building Radare2
      run: git clone --depth=1 https://github.com/radareorg/radare2 r2 ; cd r2 ; sys/install.sh > /dev/null
    - name: Testing r2pipe.py
      run: cd python ; make test
