name: CI

jobs:
  build-and-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ignore_error }}
    timeout-minutes: ${{ matrix.timeout }}
    strategy:
      fail-fast: false
      matrix:
        name: [build-and-test]
        ignore_error: [false]
        include:
          - name: linux-acr-gcc-tests
            os: ubuntu-latest
            build_system: acr
            compiler: gcc
            run_tests: true
            enabled: true
            timeout: 45

    steps:
    - uses: actions/checkout@v2
      if: matrix.enabled
    - name: Install python
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools
    - name: Building Radare2
      run: git clone --depth=1 https://github.com/radareorg/radare2 r2 ; cd r2 ; ./configure --prefix=${HOME} && make && make install
    - name: Testing r2pipe.py
      run: cd python ; make test
